# Generated by Django 4.0.6 on 2022-10-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favourite_color',
            field=models.CharField(default='', max_length=64, verbose_name='favourite color'),
        ),
    ]
