# Generated by Django 4.0.6 on 2022-10-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_favourite_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favourite_color',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='favourite color'),
        ),
    ]
