# Generated by Django 4.0.6 on 2022-10-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cartitem'),
        ('accounts', '0007_alter_customuser_favourite_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cart_items',
            field=models.ManyToManyField(to='products.cartitem'),
        ),
    ]
