# Generated by Django 4.0.6 on 2022-11-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
