# Generated by Django 4.0.6 on 2022-10-31 23:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='floofs',
        ),
        migrations.AddField(
            model_name='dog',
            name='floofs',
            field=models.ManyToManyField(related_name='dogs_floofed', to=settings.AUTH_USER_MODEL),
        ),
    ]
